# Generated by Django 5.2.1 on 2025-06-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(default='M,L,XL', max_length=50),
        ),
    ]
