# Generated by Django 5.2.3 on 2025-06-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_product_available_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unisex'), ('N', 'Not Specified'), ('K', 'Kids')], default='M', max_length=1),
        ),
    ]
