# Generated by Django 5.2.3 on 2025-06-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
